function D=load_q3_data(root)
% Q3 uses the same transport contracts as Q2 and reads relay/radio sheets.
D=load_q2_data(root);
p=fullfile(root,'input','数据','无人机应急物资运输基础数据');
c=readcell(fullfile(p,'中继无人机数据.xlsx'),'Sheet','数据','Range','A3:S3');
D.relay=struct('id',string(c{1}),'mass_kg',c{5},'speed_mps',c{6}, ...
 'cruise_kW',c{7},'energy_kWh',c{8},'reserve',c{9}/100, ...
 'prep_s',c{10},'link_s',c{11},'turn_s',c{12},'up_mps',c{13}, ...
 'down_mps',c{14},'eta',c{15},'hover_kW',c{17}, ...
 'radio_kW',c{18},'maxAGL_m',c{19});
c=readcell(fullfile(p,'中继无人机数据.xlsx'),'Sheet','数据','Range','A7:C8');
D.relayIDs=string(c(:,1)); assert(numel(D.relayIDs)==2);
c=readcell(fullfile(p,'中继无人机数据.xlsx'),'Sheet','数据','Range','A12:C12');
D.relayComponentCount=c{2};D.relayChargeFull_s=c{3};
c=readcell(fullfile(p,'通信链路参数.xlsx'),'Sheet','数据','Range','E3:E16');
v=cell2mat(c);D.radio=struct('fMHz',v(1),'system_dB',v(2), ...
 'obstruction_dB',v(3),'sensitivity_dBm',v(4),'fade_dB',v(5), ...
 'transportPt_dBm',v(6),'transportGain_dBi',v(7), ...
 'accessPt_dBm',v(8),'accessGain_dBi',v(9), ...
 'backhaulPt_dBm',v(10),'backhaulGain_dBi',v(11), ...
 'gatewayPt_dBm',v(12),'gatewayGain_dBi',v(13),'gatewayAGL_m',v(14));
assert(D.relayComponentCount==6 && D.relay.maxAGL_m>0);
end
