function q3_verify_q2_workbook(D,S,book)
% Match the supplied workbook to every detailed Q2 route and box delivery.
n=numel(S.routes);
c=readcell(book,'Sheet','Q2_运输架次','Range',sprintf('A2:H%d',n+1));
assert(size(c,1)==n,'Q2 workbook sortie count differs from detailed solution');
for p=1:n
 r=S.routes(p);st=S.sorties(p,:);
 assert(string(c{p,1})==st.sortie_id && string(c{p,2})==r.uavID ...
  &&string(c{p,3})==D.uav.id(r.typeIdx) ...
  &&string(c{p,4})==r.batteryID ...
  &&abs(c{p,5}-r.start_s)<1e-6 ...
  &&string(c{p,6})==st.service_order ...
  &&abs(c{p,7}-r.return_s)<1e-6 ...
  &&abs(c{p,8}-r.eval.energy_kWh)<1e-8, ...
  'Q2 workbook route mismatch at row %d',p);
end
c=readcell(book,'Sheet','Q2_逐箱交付','Range','A2:D81');
assert(size(c,1)==height(D.boxes),'Q2 workbook box count differs');
for b=1:height(D.boxes)
 id=string(c{b,1});ix=find(S.boxDelivery.box_id==id);
 assert(numel(ix)==1,'Q2 workbook box ID mismatch at row %d',b);
 z=S.boxDelivery(ix,:);
 assert(string(c{b,2})==z.sortie_id&&string(c{b,3})==z.area ...
  &&abs(c{b,4}-z.arrival_s)<1e-6, ...
  'Q2 workbook box delivery mismatch at row %d',b);
end
end
